import { useCallback,useEffect,useRef,useState, type FormEvent } from 'react';
import { LayoutDashboard,Users,MessagesSquare,CalendarDays,ChartNoAxesCombined,Settings,Search,Bell,ChevronDown,ChevronRight,ArrowRight,Plus,LogOut,Menu,X,CheckCircle2,AlertCircle,ShieldCheck,BookOpen,Eye,EyeOff,WifiOff,RefreshCw,ArrowUpRight } from 'lucide-react';
import { api,mutate,ApiError } from './api';
import type { Bootstrap,Page,Staff,Student } from '../shared/types';
import { Avatar } from './components';
import { errorMessage,fullName } from './utils';
import TodayPage from './TodayPage';
import AttendanceDialog from './AttendanceDialog';
import StudentDialog from './StudentDialog';
import StudentsPage from './pages/StudentsPage';
import InquiriesPage from './pages/InquiriesPage';
import SchedulePage from './pages/SchedulePage';
import ReportsPage from './pages/ReportsPage';
import SettingsPage from './pages/SettingsPage';
import './pages/pages.css';

const navigation=[{id:'today' as Page,label:'Overview',icon:LayoutDashboard},{id:'students' as Page,label:'Students & families',icon:Users},{id:'inquiries' as Page,label:'Inquiries',icon:MessagesSquare},{id:'schedule' as Page,label:'Schedule',icon:CalendarDays},{id:'reports' as Page,label:'Reports',icon:ChartNoAxesCombined}];
const validPages=new Set<Page>(['today','students','inquiries','schedule','reports','settings']);
const getPage=()=>{const p=location.hash.replace('#/','') as Page;return validPages.has(p)?p:'today';};

function Login({onLogin}:{onLogin:()=>Promise<void>}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await mutate('/auth/login',{email,password});await onLogin();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <div className="login-page"><section className="login-story"><div className="brand brand-light"><span className="brand-mark">k</span><div><strong>kumon</strong><span>CENTER WORKSPACE</span></div></div><div className="login-story-content"><div className="login-kicker">SMALL STEPS. BRIGHT FUTURES.</div><h1>A clearer view of<br/>every learning day.</h1><p>Bring your students, families, and daily center operations together in one thoughtful workspace.</p><div className="login-capabilities"><div className="login-capabilities-title">One workspace for your center</div><div className="login-capability"><span><Users size={20}/></span><div><strong>Students & families</strong><p>Keep student profiles and guardian details together.</p></div></div><div className="login-capability"><span><CalendarDays size={20}/></span><div><strong>Lessons & attendance</strong><p>Plan weekly lessons and record arrivals and departures.</p></div></div><div className="login-capability"><span><MessagesSquare size={20}/></span><div><strong>Family follow-ups</strong><p>Track inquiries and the next step for each family.</p></div></div></div></div><div className="login-story-footer">Built around the people at the heart of your center.</div></section><main className="login-form-panel"><div className="login-form-wrap"><span className="login-icon"><BookOpen size={25}/></span><div className="eyebrow">WELCOME BACK</div><h2>Your center starts here.</h2><p>Sign in to your Kumon workspace.</p><form onSubmit={submit}><div className="field"><label htmlFor="login-email">Email address</label><input id="login-email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@yourcenter.com" required autoFocus/></div><div className="field"><label htmlFor="login-password">Password</label><div className="password-field"><input id="login-password" type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary login-submit" disabled={busy}>{busy?<span className="spinner"/>:null}{busy?'Signing in…':'Sign in to workspace'}<ArrowRight size={17}/></button></form><p className="login-help">Need access? Contact your center owner.</p><div className="login-security"><ShieldCheck size={16}/><span>Private staff workspace</span></div></div><div className="login-footnote">Kumon center workspace <span>·</span> Staff access</div></main></div>;
}

export default function App(){
  const [data,setData]=useState<Bootstrap|null>(null);const [authenticated,setAuthenticated]=useState<boolean|null>(null);const [fatal,setFatal]=useState('');const [page,setPage]=useState<Page>(getPage);const [mobile,setMobile]=useState(false);const [search,setSearch]=useState('');const [searchFocus,setSearchFocus]=useState(false);const [menu,setMenu]=useState(false);const [notifications,setNotifications]=useState(false);const [studentId,setStudentId]=useState<string|null>(null);const [attendanceId,setAttendanceId]=useState<string|null>(null);const [offline,setOffline]=useState(false);const [lastSync,setLastSync]=useState<Date|null>(null);const [toast,setToast]=useState<{message:string;kind:'success'|'error'}|null>(null);const searchRef=useRef<HTMLInputElement>(null);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const notify=useCallback((message:string,kind:'success'|'error'='success')=>{setToast({message,kind});if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),5000);},[]);
  const lastActivity=useRef(Date.now());const lastSessionTouch=useRef(0);
  const refresh=useCallback(async(background=false)=>{const activityAtRequest=lastActivity.current;const unattended=background&&activityAtRequest<=lastSessionTouch.current;try{const next=await api<Bootstrap>('/bootstrap',unattended?{headers:{'x-background-request':'1'}}:{});setData(next);setAuthenticated(true);setOffline(false);setLastSync(new Date(next.serverTime));setFatal('');if(!unattended)lastSessionTouch.current=activityAtRequest;}catch(e){if(e instanceof ApiError&&e.status===401){setAuthenticated(false);setData(null);setStudentId(null);setAttendanceId(null);}else{setOffline(true);throw e;}}},[]);
  useEffect(()=>{refresh().catch(e=>{setFatal(errorMessage(e));setAuthenticated(a=>a===null?false:a);});},[refresh]);
  useEffect(()=>{if(!authenticated)return;const timer=setInterval(()=>{refresh(true).catch(()=>{});},5000);return()=>clearInterval(timer);},[authenticated,refresh]);
  useEffect(()=>{const recordActivity=(event:Event)=>{if(event.isTrusted)lastActivity.current=Date.now();};const events=['pointerdown','keydown','touchstart','wheel'];for(const name of events)window.addEventListener(name,recordActivity,{passive:true});return()=>{for(const name of events)window.removeEventListener(name,recordActivity);};},[]);
  useEffect(()=>{const listener=()=>{setPage(getPage());setMobile(false);};window.addEventListener('hashchange',listener);const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}if(e.key==='Escape'){setSearchFocus(false);setNotifications(false);setMenu(false);setMobile(false);}};window.addEventListener('keydown',keys);return()=>{window.removeEventListener('hashchange',listener);window.removeEventListener('keydown',keys);};},[]);
  const navigate=useCallback((p:Page)=>{location.hash=`/${p}`;setPage(p);setMobile(false);setSearch('');setNotifications(false);window.scrollTo({top:0});},[]);
  const onStudent=useCallback((s:Student)=>{setStudentId(s.id);setSearch('');setSearchFocus(false);},[]);
  const onAttendance=useCallback((s:Student)=>{setStudentId(null);setAttendanceId(s.id);},[]);
  const closeStudent=useCallback(()=>setStudentId(null),[]);const closeAttendance=useCallback(()=>setAttendanceId(null),[]);
  async function logout(){try{await mutate('/auth/logout',{});setData(null);setAuthenticated(false);setMenu(false);notify('You have signed out.');}catch(e){notify(errorMessage(e),'error');}}
  if(authenticated===null)return <div className="app-loading"><div className="brand-mark">k</div><span className="spinner"/><p>Opening your center workspace…</p></div>;
  if(!authenticated)return <>{fatal&&<div className="connection-error"><AlertCircle size={16}/>{fatal}<button onClick={()=>location.reload()}>Retry</button></div>}<Login onLogin={refresh}/></>;
  if(!data)return null;
  const activePage=navigation.find(n=>n.id===page);const incidents=data.incidents.filter(i=>i.status==='open');const newCount=data.inquiries.filter(i=>i.stage==='New').length;const searchResults=search.trim()?data.students.filter(s=>`${fullName(s)} ${s.studentNumber}`.toLowerCase().includes(search.toLowerCase())).slice(0,6):[];
  const props={data,refresh,notify,onStudent};const student=data.students.find(s=>s.id===studentId);const attendance=data.students.find(s=>s.id===attendanceId);
  return <div className="app-shell">{mobile&&<div className="sidebar-scrim" onClick={()=>setMobile(false)}/>}<aside className={`sidebar ${mobile?'sidebar-open':''}`}><a className="brand" href="#/today" onClick={()=>navigate('today')}><span className="brand-mark">k</span><div><strong>kumon</strong><span>CENTER WORKSPACE</span></div></a><button className="center-switch" onClick={()=>navigate('settings')}><span className="center-icon"><BookOpen size={17}/></span><span><strong>My learning center</strong><small>Center workspace</small></span><ChevronDown size={15}/></button><div className="nav-section-label">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(n=><a key={n.id} href={`#/${n.id}`} onClick={()=>navigate(n.id)} className={`nav-item ${page===n.id?'active':''}`} aria-current={page===n.id?'page':undefined}><n.icon size={19}/><span>{n.label}</span>{n.id==='inquiries'&&newCount>0&&<span className="nav-count">{newCount}</span>}{page===n.id&&<span className="nav-active-dot"/>}</a>)}</nav><div className="sidebar-bottom"><div className="setup-card"><span className="setup-icon"><ShieldCheck size={18}/></span><h3>Let's make it yours.</h3><p>Review your center settings and launch checklist.</p><button onClick={()=>navigate('settings')}>Workspace setup<ArrowUpRight size={14}/></button></div><a href="#/settings" className={`nav-item settings-link ${page==='settings'?'active':''}`} onClick={()=>navigate('settings')}><Settings size={19}/><span>Settings</span></a><div className="user-area"><button className="user-button" onClick={()=>setMenu(!menu)} aria-expanded={menu}><Avatar name={data.user.name}/><span><strong>{data.user.name}</strong><small>{data.user.role==='owner'?'Center owner':data.user.role.replace('_',' ')}</small></span><ChevronDown size={15}/></button>{menu&&<div className="user-menu"><span>{data.user.email}</span><button onClick={logout}><LogOut size={16}/>Sign out</button></div>}</div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={20}/></button><span className="breadcrumb">Workspace<ChevronRight size={13}/><strong>{page==='settings'?'Settings':activePage?.label}</strong></span></div><div className="topbar-right"><div className="global-search"><Search size={16}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} onFocus={()=>setSearchFocus(true)} onBlur={()=>setTimeout(()=>setSearchFocus(false),160)} placeholder="Search students…" aria-label="Search all students"/><kbd>⌘ K</kbd>{searchFocus&&search.trim()&&<div className="search-results"><div className="search-results-label">STUDENTS</div>{searchResults.length?searchResults.map(s=><button key={s.id} onMouseDown={e=>e.preventDefault()} onClick={()=>onStudent(s)}><Avatar name={fullName(s)} size="sm"/><span><strong>{fullName(s)}</strong><small>{s.studentNumber} · {s.grade}</small></span><ChevronRight size={15}/></button>):<p>No students match “{search}”.</p>}</div>}</div><div className="notification-wrap"><button className={`icon-button notification-button ${notifications?'is-active':''}`} onClick={()=>setNotifications(!notifications)} aria-label={`Notifications, ${incidents.length} open attendance issues`} aria-expanded={notifications}><Bell size={19}/>{incidents.length>0&&<span className="notification-dot"/>}</button>{notifications&&<div className="notifications-menu"><h3>Attendance needs attention <span>{incidents.length}</span></h3>{incidents.length?incidents.map(i=><button key={i.id} onClick={()=>{const s=data.students.find(s=>s.id===i.studentId);if(s)onStudent(s);setNotifications(false);}}><AlertCircle size={17}/><span><strong>{data.students.find(s=>s.id===i.studentId)?.firstName||'Attendance review'}</strong><small>{i.summary}</small></span><ChevronRight size={14}/></button>):<p><CheckCircle2 size={18}/>No open attendance issues.</p>}</div>}</div><div className="topbar-separator"/><span className="date-pill"><CalendarDays size={15}/>{new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:data.center.timezone}).format(new Date())}</span></div></header>
      {offline&&<div className="offline-banner" role="alert"><WifiOff size={18}/><div><strong>Connection interrupted. This roster may be out of date.</strong><span>Last updated {lastSync?.toLocaleTimeString()||'before this session'}. Use the center's approved contingency procedure. Offline recording is not available in this build.</span></div><button className="btn btn-secondary btn-sm" onClick={()=>refresh().catch(e=>notify(errorMessage(e),'error'))}><RefreshCw size={14}/>Retry</button></div>}
      <main className="page-content">{data.demo&&<div className="demo-ribbon"><span className="demo-label"><span/>Preview workspace</span><span>Sample records. Your changes are saved.</span><button onClick={()=>navigate('settings')}>View setup<ArrowRight size={12}/></button></div>}{page==='today'?<TodayPage {...props} onAttendance={onAttendance} navigate={navigate}/>:page==='students'?<StudentsPage {...props}/>:page==='inquiries'?<InquiriesPage {...props}/>:page==='schedule'?<SchedulePage {...props}/>:page==='reports'?<ReportsPage {...props}/>:<SettingsPage {...props}/>}<footer className="page-footer"><span>Kumon center workspace</span><span><span className={`mini-dot ${offline?'amber':'green'}`}/>{offline?'Connection interrupted':'Connected'} <span>·</span> {data.center.timezone.replace('_',' ')}</span></footer></main>
    </div>{student&&<StudentDialog student={student} data={data} onClose={closeStudent} onAttendance={onAttendance} refresh={refresh} notify={notify}/>} {attendance&&<AttendanceDialog student={attendance} data={data} onClose={closeAttendance} onSaved={refresh} notify={notify}/>} {toast&&<div className={`toast toast-${toast.kind}`} role={toast.kind==='error'?'alert':'status'}>{toast.kind==='success'?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>}<span>{toast.message}</span><button onClick={()=>setToast(null)} aria-label="Dismiss notification"><X size={16}/></button></div>}
  </div>;
}
