import { useMemo,useState } from 'react';
import { ArrowDownLeft,ArrowUpRight,ArrowRight,CalendarDays,Check,CheckCircle2,Clock3,Search,Users,UserPlus,MoreHorizontal,Activity,AlertTriangle,ClipboardCheck,ChevronRight,Plus,BookOpen,Settings,MessagesSquare } from 'lucide-react';
import { Avatar,Badge,SubjectTags,EmptyState } from './components';
import { mutate } from './api';
import { errorMessage,fullName,localDate,openVisit,shortTime,todayVisits } from './utils';
import type { Page,PageProps,Student } from '../shared/types';

export default function TodayPage({data,refresh,notify,onStudent,onAttendance,navigate}:{onAttendance:(s:Student)=>void;navigate:(p:Page)=>void}&PageProps){
  const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [pendingTask,setPendingTask]=useState<string|null>(null);
  const dayName=new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:data.center.timezone}).format(new Date());
  const day=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].indexOf(dayName);
  const today=todayVisits(data);const open=data.visits.filter(v=>v.status==='open');
  const expected=data.schedules.filter(s=>s.dayOfWeek===day&&s.active&&data.students.some(st=>st.id===s.studentId&&st.status==='active'));
  const expectedIds=new Set(expected.map(s=>s.studentId));const todayIds=new Set(today.map(v=>v.studentId));const openIds=new Set(open.map(v=>v.studentId));
  const verifiedIds=new Set(open.filter(v=>v.reconciliationStatus==='clear').map(v=>v.studentId));const reviewIds=new Set(open.filter(v=>v.reconciliationStatus==='review_needed').map(v=>v.studentId));
  const checkedOut=today.filter(v=>v.status==='closed');const completedIds=new Set(checkedOut.map(v=>v.studentId));
  const pending=data.tasks.filter(t=>!t.completedAt).sort((a,b)=>a.dueAt.localeCompare(b.dueAt));
  const newInquiries=data.inquiries.filter(i=>i.stage==='New');const incidents=data.incidents.filter(i=>i.status==='open');
  const roster=data.students.filter(s=>openIds.has(s.id)||(s.status==='active'&&(expectedIds.has(s.id)||todayIds.has(s.id))));
  const rows=roster.filter(s=>`${fullName(s)} ${s.studentNumber}`.toLowerCase().includes(search.toLowerCase())).filter(s=>filter==='all'||filter==='here'&&verifiedIds.has(s.id)||filter==='review'&&reviewIds.has(s.id)||filter==='expected'&&expectedIds.has(s.id)&&!todayIds.has(s.id)||filter==='out'&&completedIds.has(s.id)&&!openIds.has(s.id)).sort((a,b)=>Number(reviewIds.has(b.id))-Number(reviewIds.has(a.id))||Number(openIds.has(b.id))-Number(openIds.has(a.id))||fullName(a).localeCompare(fullName(b)));
  const recent=data.events.filter(e=>localDate(e.occurredAt,data.center.timezone)===localDate(new Date(),data.center.timezone)).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0,4);
  async function complete(id:string){setPendingTask(id);try{await mutate(`/tasks/${id}/complete`,{});await refresh();notify('Task marked complete.');}catch(e){notify(errorMessage(e),'error');}finally{setPendingTask(null);}}
  const expectedRemaining=[...expectedIds].filter(id=>!todayIds.has(id)).length;
  const emptyWorkspace=data.students.length===0&&data.inquiries.length===0&&data.schedules.length===0&&data.events.length===0&&data.visits.length===0&&data.incidents.length===0;
  if(emptyWorkspace)return <>
    <div className="page-heading"><div><div className="eyebrow">WELCOME TO YOUR WORKSPACE</div><h1>A fresh start for your center<span className="heading-dot">.</span></h1><p>Your students, families, and daily activity will come together here.</p></div></div>
    <section className="card empty-workspace-hero"><div className="empty-workspace-copy"><span className="empty-workspace-label">GETTING STARTED</span><h2>Start with your first student.</h2><p>Your directory is empty. Add a student and their guardian, then create a weekly lesson. Attendance will appear here when you record their first check-in.</p><div className="empty-workspace-actions"><button className="btn btn-primary" onClick={()=>navigate('students')}><Plus size={17}/>{data.user.role==='instructor'?'View student directory':'Add your first student'}</button><button className="btn btn-secondary" onClick={()=>navigate('settings')}>Review center setup<ArrowRight size={15}/></button></div></div><div className="empty-workspace-art" aria-hidden="true"><span className="empty-workspace-orbit"><span><Users size={20}/></span><span><CalendarDays size={18}/></span></span><span className="empty-workspace-book"><BookOpen size={46} strokeWidth={1.25}/></span></div></section>
    <div className="empty-workspace-cards"><section className="card empty-workspace-card"><span className="empty-workspace-card-icon"><Settings size={20}/></span><h2>Make it your center</h2><p>Review your center details, time zone, and the items needed before rollout.</p><button className="text-button" onClick={()=>navigate('settings')}>View center settings<ArrowRight size={14}/></button></section><section className="card empty-workspace-card"><span className="empty-workspace-card-icon purple"><MessagesSquare size={20}/></span><h2>Welcome a new family</h2><p>Record an inquiry and set a next step. Your follow-ups will appear on the overview.</p><button className="text-button" onClick={()=>navigate('inquiries')}>Open inquiry pipeline<ArrowRight size={14}/></button></section><section className="card empty-workspace-card"><span className="empty-workspace-card-icon green"><CalendarDays size={20}/></span><h2>Plan the learning week</h2><p>Once a student is added, create their recurring lessons in the calendar.</p><button className="text-button" onClick={()=>navigate('schedule')}>View weekly schedule<ArrowRight size={14}/></button></section></div>
  </>;
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span className="small-sun">✦</span> A GOOD DAY TO GROW</div><h1>Today at Kumon<span className="heading-dot">.</span></h1><p>Every student, every little step. Here's how your center is doing.</p></div><div className="page-heading-actions"><button className="btn btn-secondary" onClick={()=>navigate('schedule')}><CalendarDays size={17}/>View schedule</button><button className="btn btn-primary" onClick={()=>navigate('students')}><Plus size={18}/>Check in a student</button></div></div>
    <div className="stats-grid">
      <div className="stat-card"><div className="stat-label">Students here<span className="stat-icon stat-icon-blue"><Users size={19}/></span></div><div className="stat-value">{verifiedIds.size}<span className="live-pill"><span/>Recorded</span></div><div className="stat-foot"><span className={`mini-dot ${reviewIds.size?'amber':'green'}`}/>{reviewIds.size?`${reviewIds.size} additional ${reviewIds.size===1?'student needs':'students need'} verification`:'Recorded present, no open presence concerns'}</div></div>
      <div className="stat-card"><div className="stat-label">Expected today<span className="stat-icon stat-icon-purple"><CalendarDays size={19}/></span></div><div className="stat-value">{expectedIds.size}<span className="stat-unit">students</span></div><div className="stat-foot"><Clock3 size={13}/>{expectedRemaining} yet to arrive</div></div>
      <div className="stat-card"><div className="stat-label">Checked out<span className="stat-icon stat-icon-green"><ClipboardCheck size={19}/></span></div><div className="stat-value">{checkedOut.length}<span className="stat-unit">visits</span></div><div className="stat-foot"><CheckCircle2 size={13}/>Departures recorded today</div></div>
      <div className="stat-card"><div className="stat-label">New inquiries<span className="stat-icon stat-icon-amber"><UserPlus size={19}/></span></div><div className="stat-value">{newInquiries.length}<button className="stat-link" onClick={()=>navigate('inquiries')}>View pipeline<ArrowUpRight size={14}/></button></div><div className="stat-foot"><span className="mini-dot amber"/>Ready for a first conversation</div></div>
    </div>
    <div className="today-layout"><div className="today-primary">
      <section className="card attendance-card"><div className="card-header"><div><h2>Attendance <span className="live-marker"><span/>Live roster</span></h2><p>Your students' arrivals and departures, as they happen.</p></div><span className="card-header-icon"><Users size={19}/></span></div>
        <div className="roster-toolbar"><div className="tabs">{[['all','All students',roster.length],['here','Here now',verifiedIds.size],...(reviewIds.size?[['review','Verify presence',reviewIds.size]]:[]),['expected','Expected',expectedRemaining],['out','Checked out',[...completedIds].filter(id=>!openIds.has(id)).length]].map(([id,label,count])=><button className={`tab ${filter===id?'active':''}`} key={id} onClick={()=>setFilter(String(id))}>{label}<span className="tab-count">{count}</span></button>)}</div><div className="roster-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a student" aria-label="Find a student in today's roster"/></div></div>
        {rows.length?<div className="table-wrap"><table className="data-table roster-table"><thead><tr><th>Student</th><th>Subject</th><th>Status</th><th>Arrival</th><th className="align-right">Action</th></tr></thead><tbody>{rows.map(s=>{const visit=openVisit(data,s.id);const arrived=today.find(v=>v.studentId===s.id);const out=!visit&&!!arrived;const review=visit?.reconciliationStatus==='review_needed';return <tr key={s.id}><td><button className="student-cell" onClick={()=>onStudent(s)}><Avatar name={fullName(s)}/><span><strong>{fullName(s)}</strong><span className="cell-subtitle">{s.grade||'Student'} <span>·</span> {s.studentNumber}{s.status==='inactive'?' · Inactive enrollment':''}</span></span></button></td><td><SubjectTags subjects={s.subjects}/></td><td><Badge tone={review?'amber':visit?'green':out?'gray':'amber'}><span className="badge-dot"/>{review?'Verify presence':visit?'Here now':out?'Checked out':'Expected'}</Badge></td><td className="time-cell">{visit?shortTime(visit.checkedInAt,data.center.timezone):arrived?shortTime(arrived.checkedInAt,data.center.timezone):<span className="muted">—</span>}</td><td className="align-right">{data.user.role!=='instructor'&&<button className={`btn btn-sm ${visit?'btn-checkout':'btn-checkin'}`} onClick={()=>onAttendance(s)}>{visit?'Check out':'Check in'}{visit?<ArrowUpRight size={14}/>:<ArrowDownLeft size={14}/>}</button>}</td></tr>;})}</tbody></table></div>:<EmptyState icon={Users} title={search?'No students match your search':'All clear for now'} description={search?'Try another name or student ID.':'Students with scheduled or recorded visits will appear here.'} action={<button className="btn btn-secondary btn-sm" onClick={()=>navigate('students')}>View all students<ArrowRight size={14}/></button>}/>}
        <div className="card-footer"><span><span className="mini-dot green"/>Saved attendance updates every five seconds</span><button className="text-button" onClick={()=>navigate('reports')}>Attendance history<ArrowRight size={14}/></button></div>
      </section>
      {incidents.length>0&&<section className="card exceptions-card"><div className="card-header"><div><h2><AlertTriangle size={17}/>Needs a second look <span className="count-bubble">{incidents.length}</span></h2><p>Keep observations accurate and follow up with the center manager.</p></div></div><div className="exception-list">{incidents.map(i=>{const st=data.students.find(s=>s.id===i.studentId);return <div key={i.id}><span className="exception-symbol"><AlertTriangle size={16}/></span><div><strong>{st?fullName(st):'Attendance review'}</strong><p>{i.summary}</p></div><button className="btn btn-secondary btn-sm" onClick={()=>st&&onStudent(st)}>View record<ArrowRight size={14}/></button></div>;})}</div></section>}
    </div><aside className="today-aside">
      <section className="card followup-card"><div className="card-header"><div><h2>Your next steps <span className="count-bubble">{pending.length}</span></h2><p>A little follow-up goes a long way.</p></div></div><div className="task-list">{pending.slice(0,4).map(t=><div className="task-item" key={t.id}><button className={`task-check ${pendingTask===t.id?'is-loading':''}`} disabled={pendingTask===t.id} onClick={()=>complete(t.id)} aria-label={`Complete ${t.title}`}>{pendingTask===t.id?<span className="spinner"/>:<Check size={12}/>}</button><div><strong>{t.title}</strong><p>{t.detail}</p><span className={`task-due ${new Date(t.dueAt)<new Date()?'overdue':''}`}><Clock3 size={11}/>{localDate(t.dueAt,data.center.timezone)===localDate(new Date(),data.center.timezone)?`Today, ${shortTime(t.dueAt,data.center.timezone)}`:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:data.center.timezone}).format(new Date(t.dueAt))}</span></div></div>)}{!pending.length&&<EmptyState icon={CheckCircle2} title={data.tasks.length?'No pending follow-ups':'No follow-ups yet'} description="Create an inquiry and set a next step to add a follow-up."/>}</div><button className="aside-footer-button" onClick={()=>navigate('inquiries')}>Open inquiry pipeline<ArrowRight size={15}/></button></section>
      <section className="card activity-card"><div className="card-header"><div><h2>Recent activity</h2><p>Little moments from today.</p></div><Activity size={18}/></div><div className="activity-list">{recent.map(e=>{const s=data.students.find(s=>s.id===e.studentId);return <div className="activity-item" key={e.id}><span className={`activity-dot ${e.action==='check_in'?'activity-arrival':'activity-departure'}`}>{e.action==='check_in'?<ArrowDownLeft size={15}/>:<ArrowUpRight size={15}/>}</span><div><p><strong>{s?fullName(s):'Student'}</strong> {e.action==='check_in'?'checked in':'checked out'}</p><span>{shortTime(e.occurredAt,data.center.timezone)} <span>·</span> {e.actorName.split(' ')[0]}</span></div></div>;})}{!recent.length&&<p className="muted activity-empty">Your first arrival starts the day's story.</p>}</div></section>
      <div className="workspace-note"><div className="workspace-note-icon"><BookOpen size={20}/></div><div><strong>Room for every student to grow.</strong><p>One connected workspace for your whole center.</p></div><svg className="note-decoration" width="56" height="58" viewBox="0 0 56 58" aria-hidden="true"><path d="M8 56V32c16 0 30-12 30-28" fill="none" stroke="#aec8c8" strokeWidth="2"/><path d="M27 33C27 12 5 17 5 17c0 13 8 17 22 16ZM35 21C54 20 48 2 48 2c-11 1-16 7-13 19Z" fill="#c2d4bf"/></svg></div>
    </aside></div>
  </>;
}
