/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/bindings.generated.d.ts` (hash: a07c1241211ef0a165ca58f24b83e6fc)
interface __BaseEnv_Env {
	BACKUP_BUCKET: R2Bucket;
	CRM_DB: D1Database;
	BACKUP_QUEUE: Queue;
	ASSETS: Fetcher;
	APP_ENV: string;
	BACKUP_PROVIDER: string;
	CENTER_ID: string;
	APP_VERSION: string;
	ACCESS_ISSUER: string;
	BOOTSTRAP_OWNER_EMAIL: string;
	CF_ACCOUNT_ID: string;
	CF_DATABASE_ID: string;
	ACCESS_AUD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
