import { useEffect, useState } from 'react';
import { request, messageOf } from './api';
type Summary = { importId: string; status: string; totalRows: number; remaining: number; createdAt: string; expiresAt: string };
type History = { imports: Summary[]; total: number; page: number; pageSize: number };
export default function ImportHistory({ refreshKey, disabled, onOpen }: { refreshKey: string; disabled: boolean; onOpen: (id: string) => Promise<void> }) {
  const [page, setPage] = useState(1), [data, setData] = useState<History | null>(null), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  useEffect(() => { let current = true; setData(null); request<History>(`/api/admin/imports?page=${page}`).then(result => { if (current) { setData(result); setError(''); } }, failure => { if (current) setError(messageOf(failure)); }); return () => { current = false; }; }, [page, refreshKey, revision]);
  return <section className="card cf-settings-card" style={{ marginTop: 24 }} aria-label="Saved imports"><h2>Saved imports</h2><p>Open a receipt or reattach the original file to recover an unfinished import.</p>{error && <p className="cf-notice error" role="alert">{error}</p>}<button className="btn btn-secondary btn-sm" disabled={disabled} onClick={() => setRevision(value => value + 1)}>Refresh saved imports</button>{!data && !error ? <p role="status">Loading saved imports...</p> : data?.imports.length === 0 ? <p>No saved imports.</p> : data && <><div className="table-wrap"><table className="data-table cf-data-table"><thead><tr><th>Created</th><th>Status</th><th>Rows</th><th>Remaining</th><th>Receipt</th></tr></thead><tbody>{data.imports.map(item => <tr key={item.importId}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.status}</td><td>{item.totalRows}</td><td>{item.remaining}</td><td><button className="btn btn-secondary btn-sm" disabled={disabled} onClick={() => void onOpen(item.importId)}>Open import</button></td></tr>)}</tbody></table></div><div className="cf-pagination"><span>Page {page} of {Math.max(1, Math.ceil(data.total / data.pageSize))}</span><div><button className="btn btn-secondary btn-sm" disabled={disabled || page <= 1} onClick={() => setPage(value => value - 1)}>Previous imports</button><button className="btn btn-secondary btn-sm" disabled={disabled || page * data.pageSize >= data.total} onClick={() => setPage(value => value + 1)}>More imports</button></div></div></>}</section>;
}
