import { useState, type FormEvent } from 'react';
import { Phone, Mail, ShieldCheck, AlertTriangle, MessageSquare, Plus, ArrowRight, CalendarDays, Clock3, PencilLine } from 'lucide-react';
import { Modal, Avatar, Badge, SubjectTags, EmptyState } from './components';
import { dateLabel,errorMessage,fullName,openVisit,shortTime } from './utils';
import { mutate } from './api';
import type { Bootstrap,Student } from '../shared/types';

export default function StudentDialog({student,data,onClose,onAttendance,refresh,notify}:{student:Student;data:Bootstrap;onClose:()=>void;onAttendance:(s:Student)=>void;refresh:()=>Promise<void>;notify:(m:string,k?:'success'|'error')=>void}){
  const [tab,setTab]=useState<'overview'|'history'|'notes'>('overview');const [channel,setChannel]=useState('Phone');const [summary,setSummary]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [correcting,setCorrecting]=useState<string|null>(null);const [time,setTime]=useState('');const [reason,setReason]=useState('');const [statusBusy,setStatusBusy]=useState(false);
  const present=openVisit(data,student.id);const events=data.events.filter(e=>e.studentId===student.id);const visits=data.visits.filter(v=>v.studentId===student.id);const notes=data.interactions.filter(n=>n.studentId===student.id);const schedules=data.schedules.filter(s=>s.studentId===student.id&&s.active);
  const canOperate=data.user.role!=='instructor';
  const needsVerification=present?.reconciliationStatus==='review_needed';
  const computerTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  const timestamp=(value:string)=>new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:data.center.timezone}).format(new Date(value));
  const correctionsFor=(eventId:string)=>(data.corrections??[]).filter(c=>c.eventId===eventId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));
  const startCorrection=(eventId:string,effectiveAt:string)=>{const observed=new Date(effectiveAt);setTime(new Date(observed.getTime()-observed.getTimezoneOffset()*60000).toISOString().slice(0,16));setCorrecting(eventId);setReason('');setError('');};
  async function saveNote(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await mutate(`/students/${student.id}/interactions`,{channel,summary});await refresh();setSummary('');notify('Interaction added to the family record.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function correct(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await mutate(`/attendance/${correcting}/corrections`,{occurredAt:new Date(time).toISOString(),reason});await refresh();setCorrecting(null);setTime('');setReason('');notify('Correction recorded. The original event is preserved.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function toggleStatus(){setStatusBusy(true);try{await mutate(`/students/${student.id}`,{status:student.status==='active'?'inactive':'active'},'PATCH');await refresh();notify('Student status updated. Attendance history is retained.');}catch(e){notify(errorMessage(e),'error');}finally{setStatusBusy(false);}}
  return <Modal title="Student profile" subtitle="Family, enrollment, and attendance in one place." onClose={onClose} wide>
    <div className="profile-heading"><Avatar name={fullName(student)} size="lg"/><div className="profile-title"><h2>{fullName(student)}</h2><p>{student.studentNumber} <span>·</span> {student.grade}</p><SubjectTags subjects={student.subjects}/></div><div className="profile-heading-actions"><Badge tone={needsVerification?'amber':present?'green':student.status==='active'?'blue':'gray'}>{needsVerification?'Verify presence':present?'Here now':student.status==='active'?'Active student':'Inactive'}</Badge>{canOperate&&(present||student.status==='active')&&<button className="btn btn-primary btn-sm" onClick={()=>onAttendance(student)}>{present?'Check out':'Check in'}<ArrowRight size={15}/></button>}</div></div>
    <div className="tabs profile-tabs">{(['overview','history','notes'] as const).map(t=><button key={t} className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)}>{t==='overview'?'Overview':t==='history'?'Attendance history':'Communication log'}{t==='notes'&&<span className="tab-count">{notes.length}</span>}</button>)}</div>
    {tab==='overview'&&<div className="profile-overview">{needsVerification&&<div className="notice notice-amber"><AlertTriangle size={18}/><div><strong>Verify this student's presence</strong><p>The visit remains open and has an unresolved attendance issue. Check the room and review the events with the manager.</p></div></div>}{student.status==='inactive'&&present&&<div className="notice notice-subtle"><Clock3 size={18}/><p>The enrollment is inactive. This student still has an open visit, and their actual departure must be recorded.</p></div>}{student.pickupAlert&&<div className="notice notice-amber"><AlertTriangle size={18}/><div><strong>Pickup notice</strong><p>{student.pickupAlert}</p></div></div>}<h3 className="section-label">Family and authorized pickup</h3><div className="guardian-grid">{student.guardians.map(g=><div className="guardian-card" key={g.id}><div className="guardian-header"><Avatar name={g.name} size="sm"/><div><strong>{g.name}</strong><p>{g.relationship}</p></div></div>{g.email&&<a href={`mailto:${g.email}`}><Mail size={14}/>{g.email}</a>}{g.phone&&<a href={`tel:${g.phone}`}><Phone size={14}/>{g.phone}</a>}<div className={`pickup-permission ${g.canPickup?'allowed':'restricted'}`}><ShieldCheck size={14}/>{g.canPickup?'Authorized for pickup':'Not authorized for pickup'}</div></div>)}</div><h3 className="section-label">Weekly schedule</h3>{schedules.length?<div className="profile-slots">{schedules.map(s=><div key={s.id}><CalendarDays size={18}/><strong>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][s.dayOfWeek]}</strong><span>{s.startTime} · {s.durationMinutes} min</span><SubjectTags subjects={[s.subject]}/></div>)}</div>:<p className="muted">No recurring sessions have been scheduled yet.</p>}<div className="profile-footnote"><span>Joined {dateLabel(student.createdAt,data.center.timezone)} · {visits.length} recorded visits</span>{['owner','manager'].includes(data.user.role)&&<button className="text-button" onClick={toggleStatus} disabled={statusBusy}>{student.status==='active'?'Mark inactive':'Reactivate student'}</button>}</div></div>}
    {tab==='history'&&<>
      <p className="section-helper">Actual arrivals and departures in {data.center.timezone.replaceAll('_',' ')}. Approved corrections update the effective time; original events remain available.</p>
      {events.length?<div className="table-wrap"><table className="data-table history-table" role="table"><thead><tr><th>Event</th><th>Occurrence time</th><th>Staff</th><th></th></tr></thead><tbody>{events.map(e=>{
        const corrections=correctionsFor(e.id),latest=corrections[0],effectiveAt=latest?.correctedOccurredAt??e.occurredAt;
        const action=e.action==='check_in'?'Arrival':e.action==='exceptional_departure'?'Exceptional departure':'Departure';
        return <tr key={e.id}>
          <td data-label="Event"><span className={`event-icon ${e.action==='check_in'?'in':'out'}`}><Clock3 size={14}/></span>{action}{e.reason&&<p className="cell-subtitle">{e.reason}</p>}</td>
          <td data-label="Occurrence time">{timestamp(effectiveAt)}{latest&&<><p className="cell-subtitle"><Badge tone="blue">Corrected</Badge></p><p className="cell-subtitle">Original: {timestamp(e.occurredAt)}</p><p className="cell-subtitle">{latest.reason}</p><p className="cell-subtitle">Corrected by {latest.actorName} · {timestamp(latest.createdAt)}</p></>}
            <p className="cell-subtitle">{e.captureMode==='demo_seed'||e.captureMode==='seed'?'Demo record':e.captureMode==='staff_online'?'Saved online':e.captureMode}</p>
            {corrections.length>1&&<details><summary>{corrections.length} corrections</summary>{corrections.map(c=><div key={c.id}><p className="cell-subtitle">{timestamp(c.originalOccurredAt)} → {timestamp(c.correctedOccurredAt)}</p><p className="cell-subtitle">{c.reason}</p><p className="cell-subtitle">{c.actorName} · Recorded {timestamp(c.createdAt)}</p></div>)}</details>}
          </td>
          <td data-label="Staff">{e.actorName}</td><td>{['owner','manager'].includes(data.user.role)&&<button className="icon-button" aria-label={`Correct ${e.action} time`} onClick={()=>startCorrection(e.id,effectiveAt)}><PencilLine size={16}/></button>}</td>
        </tr>;
      })}</tbody></table></div>:<EmptyState icon={Clock3} title="No attendance yet" description="Recorded arrivals and departures will appear here."/>}
      {correcting&&<form className="correction-form" onSubmit={correct}><h3>Correct observed time</h3><p className="muted">Enter the time in your computer's time zone, {computerTimezone.replaceAll('_',' ')}. The original event remains unchanged.</p><div className="form-grid"><div className="field"><label>Actual event time<input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} required/></label></div><div className="field"><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} required minLength={8} maxLength={1000} placeholder="Explain the factual correction"/></label></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="btn btn-secondary btn-sm" type="button" disabled={busy} onClick={()=>setCorrecting(null)}>Cancel</button><button className="btn btn-primary btn-sm" disabled={busy}>{busy?'Saving correction…':'Save correction'}</button></div></form>}
    </>}
    {tab==='notes'&&<><form className="interaction-form" onSubmit={saveNote}><div className="interaction-form-heading"><MessageSquare size={18}/><h3>Log a family interaction</h3><select aria-label="Communication channel" value={channel} onChange={e=>setChannel(e.target.value)}>{['Phone','Email','Meeting','Other'].map(c=><option key={c}>{c}</option>)}</select></div><textarea aria-label="Interaction summary" value={summary} onChange={e=>setSummary(e.target.value)} rows={3} placeholder="Add the outcome and next step. Keep sensitive details to a minimum." required minLength={3}/>{error&&<p className="form-error" role="alert">{error}</p>}<div className="interaction-form-footer"><span>This is an internal log. No message is sent.</span><button className="btn btn-primary btn-sm" disabled={busy}><Plus size={15}/>Save interaction</button></div></form><div className="interaction-list">{notes.map(n=><div className="interaction-item" key={n.id}><span className="activity-dot"><MessageSquare size={15}/></span><div><div className="interaction-meta"><strong>{n.channel}</strong><span>{dateLabel(n.occurredAt,data.center.timezone)} · {n.actorName}</span></div><p>{n.summary}</p></div></div>)}{!notes.length&&<EmptyState icon={MessageSquare} title="Start the conversation history" description="Log a call or meeting to keep the team up to date."/>}</div></>}
  </Modal>;
}
