import { Building2, CheckCircle2, Clock3, Database, Globe2, LockKeyhole, MapPin, ShieldCheck, UserRound, WifiOff } from 'lucide-react';
import type { PageProps } from '../../shared/types';
import { Avatar, Badge, EmptyState } from '../components';
import { dateLabel, shortTime } from '../utils';
import { PageIntro } from './page-components';

const roleNames: Record<string, string> = { owner: 'Center owner', manager: 'Center manager', front_desk: 'Front desk', instructor: 'Instructor' };

export default function SettingsPage({ data }: PageProps) {
  const readiness = [
    { icon: LockKeyhole, title: 'Staff sign-in', description: 'Password sign-in and authenticated staff sessions are available.', status: 'Available', tone: 'green' as const },
    { icon: ShieldCheck, title: 'Multi-factor authentication', description: 'A second sign-in factor has not been implemented.', status: 'Before launch', tone: 'amber' as const },
    { icon: WifiOff, title: 'Offline attendance', description: 'The offline companion and reconciliation workflow still need to be built.', status: 'Before launch', tone: 'amber' as const },
    { icon: Database, title: 'Backup and restore', description: 'Verify backup retention and complete a restore test before using live student data.', status: 'Verification needed', tone: 'amber' as const },
    { icon: CheckCircle2, title: 'Operational acceptance', description: 'Complete center approval, pickup procedure checks, and staff training before rollout.', status: 'Review needed', tone: 'gray' as const },
  ];
  return <>
    <PageIntro eyebrow="YOUR CENTER" title="The details behind the day." description="Center information, access, and a clear view of what is ready for rollout." />
    <div className="settings-columns"><section className="card settings-center"><div className="card-header"><div><h2>Center profile</h2><p className="muted">Read-only in this first release</p></div><span className="settings-card-icon"><Building2 size={21} /></span></div><div className="center-profile-brand"><span className="center-profile-logo">K</span><div><h3>{data.center.name}</h3><Badge tone="blue">Learning center</Badge></div></div><dl className="settings-details"><div><dt><MapPin size={16} />Location</dt><dd>{data.center.location.trim() || 'Not configured'}</dd></div><div><dt><Globe2 size={16} />Time zone</dt><dd>{data.center.timezone.replaceAll('_', ' ')}</dd></div><div><dt><Clock3 size={16} />Center hours</dt><dd>{data.center.operatingHours.trim() || 'Not configured'}</dd></div><div><dt><Database size={16} />Data environment</dt><dd><Badge tone={data.demo ? 'amber' : 'green'}>{data.demo ? 'Demo data' : 'Center data'}</Badge></dd></div></dl>{data.demo && <div className="notice-box">This workspace contains sample students and families. Keep real student information out until the launch review is complete.</div>}</section>
      <section className="card settings-account"><div className="card-header"><div><h2>Your access</h2><p className="muted">Currently signed-in staff member</p></div><span className="settings-card-icon"><UserRound size={21} /></span></div><div className="staff-profile"><Avatar name={data.user.name} size="lg" /><h3>{data.user.name}</h3><p>{data.user.email}</p><Badge tone="purple">{roleNames[data.user.role] || data.user.role}</Badge></div><div className="account-note"><LockKeyhole size={17} /><p>Actions are attributed to your account in the activity log. Use your own staff login.</p></div></section></div>
    <section className="card readiness-card"><div className="card-header"><div><h2>Launch readiness</h2><p className="muted">This build is a working foundation. These items still need attention before center rollout.</p></div><Badge tone="amber">In development</Badge></div><div className="readiness-list">{readiness.map(({ icon: Icon, title, description, status, tone }) => <div className="readiness-row" key={title}><span className={`readiness-icon ${tone}`}><Icon size={19} /></span><div><h3>{title}</h3><p>{description}</p></div><Badge tone={tone}>{status}</Badge></div>)}</div></section>
    <section className="card audit-card"><div className="card-header"><div><h2>Recent activity</h2><p className="muted">Recorded changes across your center</p></div><span className="count-pill">{data.audit.length}</span></div>{data.audit.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Staff member</th><th>Action</th><th>Detail</th><th>Recorded</th></tr></thead><tbody>{[...data.audit].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 30).map(entry => <tr key={entry.id}><td><span className="audit-actor"><Avatar name={entry.actorName} size="sm" />{entry.actorName}</span></td><td><span className="audit-action">{entry.action.replace(/[._]/g, ' ')}</span></td><td className="audit-detail">{entry.detail || 'No additional detail'}</td><td><span className="table-text-stack"><span>{dateLabel(entry.createdAt, data.center.timezone)}</span><small>{shortTime(entry.createdAt, data.center.timezone)}</small></span></td></tr>)}</tbody></table></div> : <EmptyState icon={Clock3} title="Your activity log starts here" description="Changes to students, inquiries, schedules, and attendance will appear as your team works." />}{data.audit.length > 30 && <div className="table-footer">Showing the 30 most recent changes.</div>}</section>
  </>;
}
