import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, BookOpen, KeyRound, LockKeyhole, ShieldCheck, Tablet, Users } from 'lucide-react';

export function StaffSignIn({ error, retry, pending = false }: { error?: string; retry: () => void; pending?: boolean }) {
  return <div className="cf-access-page"><section className="cf-access-story"><a className="brand brand-light" href="/admin"><span className="brand-mark">k</span><div><strong>kumon</strong><span>CENTER WORKSPACE</span></div></a><div><span className="eyebrow">YOUR CENTER, TOGETHER</span><h1>A clearer view of<br />every learning day.</h1><p>Manage students and families with the staff account your center has approved.</p><div className="cf-access-features"><span><Users size={20} />Students and guardians</span><span><BookOpen size={20} />Observed attendance</span><span><ShieldCheck size={20} />Individual staff access</span></div></div><small>Private staff workspace</small></section><main className="cf-access-form"><span className="cf-large-icon"><LockKeyhole size={26} /></span><div className="eyebrow">STAFF ACCESS</div><h2>Sign in to your center.</h2><p>Continue with your center's approved sign-in provider.</p><a className="btn btn-primary" href="/cdn-cgi/access/login" target={pending ? '_blank' : undefined} rel={pending ? 'noopener' : undefined}>Continue to staff sign-in<ArrowRight size={16} /></a>{pending && <div className="cf-notice amber">A request still needs confirmation. Keep this tab open, sign in using the new tab, then return here and choose “Already signed in? Try again.”</div>}{error && <p className="form-error" role="alert">{error}</p>}<button className="text-button" onClick={retry}>Already signed in? Try again</button><div className="cf-access-help">For front desk check-ins, <a href="/kiosk">open the kiosk</a>.</div></main></div>;
}

export function KioskEnroll({ onEnroll, busy, error }: { onEnroll: (code: string) => Promise<void>; busy: boolean; error: string }) {
  const [code, setCode] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); void onEnroll(code.trim()); };
  return <main className="cf-device-page"><div className="cf-device-card card"><span className="cf-large-icon"><Tablet size={28} /></span><div className="eyebrow">FRONT DESK SETUP</div><h1>Connect this kiosk.</h1><p>A center owner can create a one-time enrollment code from staff settings.</p><form onSubmit={submit}><label className="field"><span>Enrollment code</span><input autoFocus autoComplete="off" spellCheck={false} required value={code} maxLength={128} onChange={event => setCode(event.target.value)} placeholder="Enter the code from your owner" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy || !code.trim()}>{busy ? 'Connecting...' : 'Connect this kiosk'}<ArrowRight size={16} /></button></form><a className="text-button" href="/admin">Open staff workspace</a></div><p className="cf-device-note">Enroll only a device managed by your center.</p></main>;
}

export function KioskUnlock({ centerName, deviceName, staff, onUnlock, onRefresh, busy, error, pending }: { centerName: string; deviceName: string; staff: { id: string; name: string }[]; onUnlock: (staffId: string, pin: string) => Promise<void>; onRefresh: () => void; busy: boolean; error: string; pending: boolean }) {
  const [staffId, setStaffId] = useState(staff[0]?.id || '');
  const [pin, setPin] = useState('');
  useEffect(() => { if (!staff.some(person => person.id === staffId)) setStaffId(staff[0]?.id || ''); }, [staff, staffId]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (busy) return; await onUnlock(staffId, pin); setPin(''); };
  return <main className="cf-device-page"><div className="cf-device-card card"><span className="cf-large-icon"><KeyRound size={27} /></span><div className="eyebrow">{deviceName || 'FRONT DESK KIOSK'}</div><h1>{centerName || 'Your center'}</h1><p>{staff.length ? 'Choose your name and enter your individual staff PIN.' : 'Your center owner needs to enable kiosk access for at least one staff member.'}</p>{pending && <div className="cf-notice amber">An attendance request is awaiting confirmation. Sign in as the same staff member to resolve it before recording another action.</div>}{staff.length ? <form onSubmit={submit}><label className="field"><span>Staff member</span><select required value={staffId} onChange={event => setStaffId(event.target.value)}>{staff.map(person => <option value={person.id} key={person.id}>{person.name}</option>)}</select></label><label className="field"><span>Your PIN</span><input required type="password" inputMode="numeric" pattern="[0-9]{8,12}" minLength={8} maxLength={12} autoComplete="off" value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, ''))} placeholder="8 to 12 digits" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy || !staffId || pin.length < 8}>{busy ? 'Unlocking...' : 'Unlock front desk'}<ArrowRight size={16} /></button></form> : <div className="cf-notice">In the staff workspace, open Center settings, choose Manage beside a staff member, enable kiosk access, and set their individual PIN.</div>}{!staff.length && error && <p className="form-error" role="alert">{error}</p>}<button className="text-button" disabled={busy} onClick={onRefresh}>Refresh staff list</button><span className="cf-device-note"><LockKeyhole size={13} />The kiosk locks when it is not in use.</span></div><a className="text-button" href="/admin">Open staff workspace</a></main>;
}
